name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Rust 1.65
      run: rustup set profile default && rustup default 1.65.0
    - name: Check code formatting
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --examples --bins --all-features --quiet
    - name: Build documentation
      run: cargo doc --no-deps --quiet
    - name: Run tests
      run: cargo test --release --quiet
    - name: Code analysis
      run: cargo clippy --all-features --quiet
